---
- hosts: all
  become: True
  tasks:
    - name: Install python pip
      apt:
        name: python-pip
        state: present
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: gameoflife
        image: "raghudusa/helloworld:19052021"
        state: started
        published_ports:
          - 0.0.0.0:8086:8080
